name: "\U0001F4A5 Отчет об ошибке"              
title: "\U0001F4A5 [Bug]: "
description: Create a report.
labels: ["💡 Bug"]

body:
#  - type: markdown
#    id: notice
#    attributes:
#      value: |
#        ### Новый отчёт о баге
#        Привет друг! Здесь ты должен подробно описать суть проблемы, которую ты нашел в лаунчере. Чем информативнее отчет, тем быстрее пофиксится баг.
  - type: textarea
    id: description
    attributes:
      label: "Описание проблемы"
      description: "Подробно объясните, что произошло"
      placeholder: "Тут пишем текст"
    validations:
      required: true
  - type: markdown
    id: image_section
    attributes:
      value: |
        ### 🖼️ Прикрепите картинку к описанию проблемы (если необходимо)
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Шаги воспроизведения
      description: "Опишите здесь подробно, какие шаги вы произвели с появлением проблемы"
      placeholder: | 
          1. Открыл лаунчер
          2. Зашёл в аккаунт
          3. Получил ошибку при запуске игры
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Логи лаунчера(опционально)
      description: "Здесь нужно показать логи последней сессии(с ошибкой) лаунчера. Найти их можно в папке лаунчера"
      placeholder: | 
          [18.12.2024 19:33:07] [INFO] Лаунчер Gambit Role Play запущен, разрешение лаунчера изменено на 1100x800
          [18.12.2024 19:33:07] [INFO] Идентификатор текущей сессии: b7953bc9
          [18.12.2024 19:33:07] [INFO] Браузер CEF создан и инициализирован, запуск инициализации лаунчера
          [18.12.2024 19:33:10] [INFO] internal/update/version
    validations:
      required: true
